app:
  local-url: http://localhost:${server.port}
server:
  port: 2020
spring:
  application:
    name: spring-rest-security
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/accountMVC
    username: postgres
    password: waris
    driver-class-name: org.postgresql.Driver
#    initialization-mode: always
    data: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl_auto: update
    show_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enabled: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: tgm.push@gmail.com
    password: tgm_push!123
security:
  jwt:
    secret-key: account
springdoc:
  swagger-ui:
    path: /swagger-ui.html





